### ISSUE TITLE
Quadro Control Cards do not show fan RPM

### ISSUE THREAD

**Issue by kwork-er** [medevil84/FanControl.AquacomputerDevices#2]
Hi, first off, thank you very much for this nice plugin and the effort put into it!
I recently got an Aquacomputer Quadro and noticed that on the four cards that are displayed for it, the fan RPM is not shown like it is for fans FanControl recognizes natively through MB headers.
This does not seem to harm general functionality, but being able to see each fans RPM certainly would come in very handy during the controls setup.
The data for fan RPM seems to be there already, as e.g. HFiNFO can read it from a Quadro (not sure about other AC devices), and so I would hope implementing RPM display might not be too much of a big deal?

**Comment by medevil84** [comment]
The fan speed and fan control are two separate items and must be manually (or automatically) associated. In order to do this, click on the three dots button in the speed control, click on "Pair speed sensor..." and select the relative fan speed sensor. If you didn't change the labels, you can pair "Quadro Controller Power 1" with "Quadro Fan 1" and so on.
After this, speed will be reported on the control card too.

**Comment by kwork-er** [comment]
A classic case of pebkac.. I did not even realize the sensors were not paired.
Assigning the correct ones was not the issue in my case as I like to maintain at least part of any initial order. What seems odd is that in the speed cards there are sensors labeled 'Quadro Fan 1' through 4, the Quadros flow sensor and then four more generic 'Fan 1' through 4 speeds, which are showing the exact same values as the former Quadro fans. Is that expected?
Anyways, this one is invalid, clearly. Perhaps No1 for the FAQ section at best ;)
Thanks again

**Comment by medevil84** [comment]
Actually, FanControl (or rather, the LibreHardwareMonitor library it uses) natively supports reading from the Quadro sensor, so you'll get 4 more readings if the "Controller" settings are ticked in the app. Personally, I've disabled this option because I don't have any other sensors reported, but this may not be feasible for all users.
I'll sure review the readme and add those two faqs :)
